# Generated by Django 4.0.4 on 2022-05-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
    ]
